apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notebook-data
  namespace: datalake
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
