apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-nessie
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jyorko/datalake
    targetRevision: HEAD
    path: application-charts/nessie
    helm:
      repoURL: https://charts.projectnessie.org
      chart: nessie
      valueFiles:
        - values.yaml
  destination:
    namespace: datalake
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
